<a href="https://colab.research.google.com/github/CatalinaIguaC12/Ejercicios-BIT-Catalina-Igua/blob/main/Taller_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**CONTAMINACIÓN DEL AIRE**

La contaminación del aire es una de las mayores amenazas ambientales para la salud. La exposición a contaminantes como el material particulado (PM2.5),el dióxido de nitrógeno (NO₂), el ozono (O₃) y el monoxido de carbono (CO) puede causar:

1. Afectación a pulmones y corazón, pueden causar enfermedades graves y muerte prematura.
2. Irrita ojos y vías respiratorias, dificultan la respiración.
3. Inflama los pulmones y empeora el asma, aumentan infecciones respiratorias.
4. Reducen el oxígeno en la sangre; pueden causar mareos, desmayos y en casos graves, muerte.

El AQI(Air Quality Index) es un valor numérico adimensional que resume la concentración de varios contaminantes atmosféricos en un solo indicador fácil de interpretar.

Se estima mediante funciones estandarizadas definidas por agencias ambientales como la Environmental Protection Agency (EPA) y la Organización Mundial de la Salud (OMS).

Los rangos del AQI son:

1. 0- 50: Aire limpio sin riesgo para la salud
2. 51 – 100: Riesgo bajo para la población general.
3. 101 – 150: Puede afectar a personas vulnerables.
4. 151 – 200: Afecta a toda la población.
5. 201 – 300: Riesgo significativo para la salud.
6. 301 – 500: Emergencia sanitaria.


Los datos que se presentan a continuación corresponden a los valores del Índice de Calidad del Aire (AQI) en diferentes ciudades alrededor del mundo.

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
datos=pd.read_csv('/content/drive/MyDrive/TALLER/global air pollution dataset.csv')
datos

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category
0,Russian Federation,Praskoveya,51,Moderate,1,Good,36,Good,0,Good,51,Moderate
1,Brazil,Presidente Dutra,41,Good,1,Good,5,Good,1,Good,41,Good
2,Italy,Priolo Gargallo,66,Moderate,1,Good,39,Good,2,Good,66,Moderate
3,Poland,Przasnysz,34,Good,1,Good,34,Good,0,Good,20,Good
4,France,Punaauia,22,Good,0,Good,22,Good,0,Good,6,Good
...,...,...,...,...,...,...,...,...,...,...,...,...
23458,India,Gursahaiganj,184,Unhealthy,3,Good,154,Unhealthy,2,Good,184,Unhealthy
23459,France,Sceaux,50,Good,1,Good,20,Good,5,Good,50,Good
23460,India,Mormugao,50,Good,1,Good,22,Good,1,Good,50,Good
23461,United States of America,Westerville,71,Moderate,1,Good,44,Good,2,Good,71,Moderate
23462,Malaysia,Marang,70,Moderate,1,Good,38,Good,0,Good,70,Moderate

Se revisaron los datos nulos y la estructura del Dataset

In [4]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23463 entries, 0 to 23462
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country             23036 non-null  object
 1   City                23462 non-null  object
 2   AQI Value           23463 non-null  int64
 3   AQI Category        23463 non-null  object
 4   CO AQI Value        23463 non-null  int64
 5   CO AQI Category     23463 non-null  object
 6   Ozone AQI Value     23463 non-null  int64
 7   Ozone AQI Category  23463 non-null  object
 8   NO2 AQI Value       23463 non-null  int64
 9   NO2 AQI Category    23463 non-null  object
 10  PM2.5 AQI Value     23463 non-null  int64
 11  PM2.5 AQI Category  23463 non-null  object
dtypes: int64(5), object(7)
memory usage: 2.1+ MB

El dataset tiene 23.463 filas, pero las columnas Country y City no están completamente diligenciadas, ya que tienen 23.036 y 23.462 datos, lo que indica que hay valores faltantes.

Se realizó validacion empleando .isnull()

In [5]:
datos.isnull().sum()

Country               427
City                    1
AQI Value               0
AQI Category            0
CO AQI Value            0
CO AQI Category         0
Ozone AQI Value         0
Ozone AQI Category      0
NO2 AQI Value           0
NO2 AQI Category        0
PM2.5 AQI Value         0
PM2.5 AQI Category      0
dtype: int64

Se eliminaron los registros sin pais y sin ciudad, por que sin esta informacion no es posible realizar comparaciones.

In [6]:
datos=datos.dropna(subset=['Country'])
datos.isnull().sum()

Country               0
City                  1
AQI Value             0
AQI Category          0
CO AQI Value          0
CO AQI Category       0
Ozone AQI Value       0
Ozone AQI Category    0
NO2 AQI Value         0
NO2 AQI Category      0
PM2.5 AQI Value       0
PM2.5 AQI Category    0
dtype: int64

In [7]:
datos=datos.dropna(subset=['City'])
datos.isnull().sum()

Country               0
City                  0
AQI Value             0
AQI Category          0
CO AQI Value          0
CO AQI Category       0
Ozone AQI Value       0
Ozone AQI Category    0
NO2 AQI Value         0
NO2 AQI Category      0
PM2.5 AQI Value       0
PM2.5 AQI Category    0
dtype: int64

Se utilizó la función .duplicated() para verificar si existían ciudades repetidas en el conjunto de datos, con el fin de determinar la necesidad de calcular promedios. Sin embargo, no se identificaron duplicados en esta información.

In [8]:
datos['City'].duplicated().sum()

np.int64(0)

Para evitar confusiones en el análisis de la información, se empleó la función .replace() con el fin de modificar los valores de la columna AQI Category y así facilitar su interpretación.

Para ello fue necesario:

1. Identificar las diferentes categorias que tiene la columna AQI Category, empleando .value_counts().

In [9]:
datos['AQI Category'].value_counts()

AQI Category
Good                              9688
Moderate                          9087
Unhealthy                         2215
Unhealthy for Sensitive Groups    1568
Very Unhealthy                     286
Hazardous                          191
Name: count, dtype: int64

2. Se empleó la función .replace() para cambiar las catergorias de la columna AQI Category

In [10]:
datos['AQI Category'] = datos['AQI Category'].str.strip()

In [11]:
datos['AQI Category']= datos['AQI Category'].str.replace('Unhealthy for Sensitive Groups','Dañino para grupos sensibles')
datos['AQI Category']= datos['AQI Category'].str.replace('Dañino for Sensitive Groups','Dañino para grupos sensibles')
datos['AQI Category']= datos['AQI Category'].str.replace('Very Unhealthy','Muy dañino')
datos['AQI Category']= datos['AQI Category'].str.replace('Very Dañino','Muy dañino')
datos['AQI Category']= datos['AQI Category'].str.replace('Unhealthy','Dañino')
datos['AQI Category']= datos['AQI Category'].str.replace('Good','Bueno')
datos['AQI Category']= datos['AQI Category'].str.replace('Moderate','Moderado')
datos['AQI Category']= datos['AQI Category'].str.replace('Hazardous','Peligroso')
datos['AQI Category'].value_counts()

AQI Category
Bueno                           9688
Moderado                        9087
Dañino                          2215
Dañino para grupos sensibles    1568
Muy dañino                       286
Peligroso                        191
Name: count, dtype: int64

Se incorporaron dos nuevas columnas en la tabla, Contaminante_Mayor y Valor_Max_Contaminante, como un resumen de los datos más relevantes por cada ciudad, con el fin de facilitar el análisis de la información.

In [12]:
datos['Contaminante_Mayor'] = datos[
    ['CO AQI Value', 'Ozone AQI Value', 'NO2 AQI Value', 'PM2.5 AQI Value']
].idxmax(axis=1)

datos

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category,Contaminante_Mayor
0,Russian Federation,Praskoveya,51,Moderado,1,Good,36,Good,0,Good,51,Moderate,PM2.5 AQI Value
1,Brazil,Presidente Dutra,41,Bueno,1,Good,5,Good,1,Good,41,Good,PM2.5 AQI Value
2,Italy,Priolo Gargallo,66,Moderado,1,Good,39,Good,2,Good,66,Moderate,PM2.5 AQI Value
3,Poland,Przasnysz,34,Bueno,1,Good,34,Good,0,Good,20,Good,Ozone AQI Value
4,France,Punaauia,22,Bueno,0,Good,22,Good,0,Good,6,Good,Ozone AQI Value
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23458,India,Gursahaiganj,184,Dañino,3,Good,154,Unhealthy,2,Good,184,Unhealthy,PM2.5 AQI Value
23459,France,Sceaux,50,Bueno,1,Good,20,Good,5,Good,50,Good,PM2.5 AQI Value
23460,India,Mormugao,50,Bueno,1,Good,22,Good,1,Good,50,Good,PM2.5 AQI Value
23461,United States of America,Westerville,71,Moderado,1,Good,44,Good,2,Good,71,Moderate,PM2.5 AQI Value
23462,Malaysia,Marang,70,Moderado,1,Good,38,Good,0,Good,70,Moderate,PM2.5 AQI Value

In [13]:
datos['Valor_Max_Contaminante'] = datos[
    ['CO AQI Value', 'Ozone AQI Value', 'NO2 AQI Value', 'PM2.5 AQI Value']
].max(axis=1)

datos

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category,Contaminante_Mayor,Valor_Max_Contaminante
0,Russian Federation,Praskoveya,51,Moderado,1,Good,36,Good,0,Good,51,Moderate,PM2.5 AQI Value,51
1,Brazil,Presidente Dutra,41,Bueno,1,Good,5,Good,1,Good,41,Good,PM2.5 AQI Value,41
2,Italy,Priolo Gargallo,66,Moderado,1,Good,39,Good,2,Good,66,Moderate,PM2.5 AQI Value,66
3,Poland,Przasnysz,34,Bueno,1,Good,34,Good,0,Good,20,Good,Ozone AQI Value,34
4,France,Punaauia,22,Bueno,0,Good,22,Good,0,Good,6,Good,Ozone AQI Value,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23458,India,Gursahaiganj,184,Dañino,3,Good,154,Unhealthy,2,Good,184,Unhealthy,PM2.5 AQI Value,184
23459,France,Sceaux,50,Bueno,1,Good,20,Good,5,Good,50,Good,PM2.5 AQI Value,50
23460,India,Mormugao,50,Bueno,1,Good,22,Good,1,Good,50,Good,PM2.5 AQI Value,50
23461,United States of America,Westerville,71,Moderado,1,Good,44,Good,2,Good,71,Moderate,PM2.5 AQI Value,71
23462,Malaysia,Marang,70,Moderado,1,Good,38,Good,0,Good,70,Moderate,PM2.5 AQI Value,70

**PREGUNTAS:**

1. ¿Cuales son los 10 paises con peor calidad del aire?

In [14]:
paises_contaminacion_mayor= datos.groupby('Country')['AQI Value'].mean().sort_values(ascending=False)
print(paises_contaminacion_mayor.head(10))

Country
Republic of Korea       421.000000
Bahrain                 188.000000
Mauritania              179.000000
Pakistan                178.788274
United Arab Emirates    163.666667
Aruba                   163.000000
Kuwait                  162.000000
Qatar                   157.500000
India                   152.964228
Senegal                 152.424242
Name: AQI Value, dtype: float64

Rta: Los paises con peor calidad del aire son Republica de Corea, Baréin, Mauritania, Pakistan, Emiratos Árabes Unidos, Aruba, Kuwait, Catar, India y Senegal

A continuación se relacionan los datos especificos de la Republica de Corea:

In [15]:
datos[datos['Country'] == 'Republic of Korea']

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category,Contaminante_Mayor,Valor_Max_Contaminante
1402,Republic of Korea,Seoul,421,Peligroso,27,Good,0,Good,91,Moderate,415,Hazardous,PM2.5 AQI Value,415

2. ¿Cuales son los 10 paises con mejor calidad del aire?

In [16]:
paises_contaminacion_menor= datos.groupby('Country')['AQI Value'].mean().sort_values(ascending=True)
print(paises_contaminacion_menor.head(10))

Country
Palau                               16.000000
Solomon Islands                     18.000000
Maldives                            19.000000
Iceland                             23.000000
Bolivia (Plurinational State of)    23.787879
Papua New Guinea                    24.866667
Seychelles                          26.000000
Bhutan                              26.000000
Uruguay                             26.653846
Argentina                           28.235294
Name: AQI Value, dtype: float64

Rta: Los paises con mejor calidad del aires son Palaos, Islas Salomón, Maldivas, Islandia,Bolivia, Papúa Nueva Guinea, Seychelles, Bután, Uruguay y
Argentina

3. ¿Cual es el contaminante que más se repite?

In [17]:
datos['Contaminante_Mayor'].value_counts()

Contaminante_Mayor
PM2.5 AQI Value    17997
Ozone AQI Value     5037
NO2 AQI Value          1
Name: count, dtype: int64

Rta: El contaminante que más se repite es PM2.5. El CO no aparece dentro del conteo, debido a que siempre fue el contaminante con menor presencia en cada ciudad.

4. ¿Qué ciudad tiene el valor de CO más alto?

In [18]:
datos.sort_values(by='CO AQI Value', ascending=False)[
    ['Country', 'City', 'CO AQI Value', 'AQI Category']
].head(10)

,Country,City,CO AQI Value,AQI Category
5156,United States of America,Durango,133,Peligroso
12800,Malaysia,Miri,67,Muy dañino
13398,Democratic Republic of the Congo,Kasongo Lunda,51,Peligroso
18160,South Africa,Boksburg,49,Peligroso
13447,South Africa,Alberton,41,Muy dañino
19641,South Africa,Soweto,36,Dañino
14678,Democratic Republic of the Congo,Bulungu,35,Peligroso
277,South Africa,Balfour,31,Peligroso
11867,China,Chengdu,28,Peligroso
8835,Chile,Lampa,28,Peligroso

In [19]:
datos[datos['City'] == 'Durango']

,Country,City,AQI Value,AQI Category,CO AQI Value,CO AQI Category,Ozone AQI Value,Ozone AQI Category,NO2 AQI Value,NO2 AQI Category,PM2.5 AQI Value,PM2.5 AQI Category,Contaminante_Mayor,Valor_Max_Contaminante
5156,United States of America,Durango,500,Peligroso,133,Unhealthy for Sensitive Groups,0,Good,53,Moderate,500,Hazardous,PM2.5 AQI Value,500

Rta: La ciudad con mayor nivel de CO es Durango (Estados Unidos)

5. ¿Cuales son las 10 ciudades con mas contaminación y que contaminante predomina en cada una de ellas?

In [20]:
ciudades_mas_conta = datos.groupby('City')['AQI Value'].mean() \
    .sort_values(ascending=False).head(10)

print(ciudades_mas_conta)

City
Dataganj        500.0
Chhachhrauli    500.0
Sasni           500.0
Rohtak          500.0
Faridabad       500.0
Nagaur          500.0
Bareli          500.0
Churu           500.0
Phalodi         500.0
Kakrala         500.0
Name: AQI Value, dtype: float64

In [21]:
resultado = datos[datos['City'].isin(ciudades_mas_conta.index)][
    ['City', 'Country', 'AQI Value', 'Contaminante_Mayor', 'PM2.5 AQI Value']
]

print(resultado)

               City Country  AQI Value Contaminante_Mayor  PM2.5 AQI Value
714         Kakrala   India        500    PM2.5 AQI Value              478
1127         Nagaur   India        500    PM2.5 AQI Value              426
1561       Dataganj   India        500    PM2.5 AQI Value              437
2297        Phalodi   India        500    PM2.5 AQI Value              467
2858         Bareli   India        500    PM2.5 AQI Value              478
5475   Chhachhrauli   India        500    PM2.5 AQI Value              461
6657          Churu   India        500    PM2.5 AQI Value              500
7133         Rohtak   India        500    PM2.5 AQI Value              467
15591     Faridabad   India        500    PM2.5 AQI Value              500
20567         Sasni   India        500    PM2.5 AQI Value              433

Las ciudades con mayor nivel de contaminacion son: Kakrala,Nagaur,Dataganj,Phalodi,Bareli,Chhachhauli,Churu, Rohtak,Faridabad y Sasni, las cuales se encuentran en India y el contaminante que predomina en cada ciudad es PM2.5

6. ¿Cuales son las 10 ciudades menos contaminadas y que contaminante predomina en cada una de ellas?

In [22]:
ciudades_menos_contaminadas = datos.groupby('City')['AQI Value'].mean() \
    .sort_values(ascending=True).head(10)

print(ciudades_menos_contaminadas)

City
El Torno         6.0
Macas            7.0
Azogues          8.0
Tari             8.0
Huaraz           9.0
Huancavelica    10.0
Puerto Asis     10.0
Junin           10.0
Guapi           10.0
Nueva Loja      10.0
Name: AQI Value, dtype: float64

In [23]:
resultado = datos[datos['City'].isin(ciudades_menos_contaminadas.index)][
    ['City', 'Country', 'AQI Value', 'Contaminante_Mayor']
]

print(resultado)

               City                           Country  AQI Value  \
512        El Torno  Bolivia (Plurinational State of)          6
3564     Nueva Loja                           Ecuador         10
7486         Huaraz                              Peru          9
7792   Huancavelica                              Peru         10
9194          Macas                           Ecuador          7
11769   Puerto Asis                          Colombia         10
14502       Azogues                           Ecuador          8
15578         Junin                              Peru         10
16830         Guapi                          Colombia         10
23269          Tari                  Papua New Guinea          8

      Contaminante_Mayor
512      PM2.5 AQI Value
3564     PM2.5 AQI Value
7486     Ozone AQI Value
7792     PM2.5 AQI Value
9194     Ozone AQI Value
11769    PM2.5 AQI Value
14502    PM2.5 AQI Value
15578    PM2.5 AQI Value
16830    Ozone AQI Value
23269    Ozone AQI Value

Rta: Las ciudades con mejor calidad del aire son: El Torno, Nueva Loja, Huaraz, Huancavelica, Macas, Puerto Asis, Azogues, Junin. Guapi y Tari, las cuales se encuentran en america del sur y el contaminante que predomina en cada ciudad es PM2.5

**CONCLUSIONES **

1. El ejercicio presenta algunas limitaciones debido a que la cantidad de datos no es igual para todos los paises analizados. Mientras algunos tienen muy pocos registros, otros cuentan con mucha más información, lo que genera un desbalance en el análisis.
Por esta razón, usar promedios no resulta adecuado, ya que en los casos con muchos datos los valores se promedian y pueden perder detalles importantes, mientras que en los que tienen pocos datos, un solo valor puede influir demasiado en el resultado. Esto hace que la comparación no sea del todo justa ni representativa.
En ese sentido, se optó por analizar los datos tal como se presentan, teniendo en cuenta su contexto, y reconociendo que para hacer comparaciones más precisas sería necesario contar con una cantidad de información más equilibrada.

2. El PM2.5 es el contaminante que se presenta en mayor cantidad a nivel mundial debido a su origen, ya que se genera a partir de diversas fuentes como la actividad industrial, el uso de vehículos que dependen de combustibles, los incendios forestales, entre otras. Adicionalmente, debido a su tamaño reducido, puede permanecer suspendido en el aire por más tiempo, lo que favorece su acumulación y presencia en diferentes regiones.

3. Aunque el contaminante más común es el PM2.5, la categoría de calidad del aire (AQI) que predomina a nivel mundial es “Bueno”, lo cual indica que, en la mayoría de los casos, este contaminante no se encuentra en niveles peligrosos.
No obstante, existen territorios donde los niveles de PM2.5 alcanzan categorías críticas. En el caso de India, se presentan condiciones clasificadas como “Peligroso”, lo que evidencia la necesidad de implementar medidas orientadas a la reducción de este contaminante en el aire. Esta situación puede generar efectos nocivos tanto en la salud humana como en los ecosistemas, afectando a las diferentes especies que habitan en ellos.