**Taller Integrador – Consumo de APIs + Power BI**

Realicé el ejercicio empleando la API: Free Fake REST API for Placeholder JSON Data (https://dummyjson.com)

1. Importación de librerias

In [1]:
import requests
import pandas as pd

2. Empleando el endpoint /products se consultaron los productos disponibles en la API. Con el parámetro limit=100 se obtuvieron los primeros 100 registros. Posteriormente, se realizó la primera consulta a la API y se validó el status_code para confirmar que la respuesta fue exitosa.

In [2]:
base_url = "https://dummyjson.com"
endpoint = "/products"
url = base_url + endpoint+"?limit=100"
response = requests.get(url)
print("Status code:", response.status_code)

Status code: 200

3. La respuesta en formato JSON se convirtió en un DataFrame para poder visualizar la información de manera más organizada. Sin embargo, se observó que los datos se encontraban dentro de un diccionario, por lo que se extrajo la información correspondiente a los productos para poder trabajar con ella y utilizarla en el análisis.

In [3]:
data = response.json()
df = pd.DataFrame(data)
df.head()

                                            products  total  skip  limit
0  {'id': 1, 'title': 'Essence Mascara Lash Princ...    194     0    100
1  {'id': 2, 'title': 'Eyeshadow Palette with Mir...    194     0    100
2  {'id': 3, 'title': 'Powder Canister', 'descrip...    194     0    100
3  {'id': 4, 'title': 'Red Lipstick', 'descriptio...    194     0    100
4  {'id': 5, 'title': 'Red Nail Polish', 'descrip...    194     0    100

In [4]:
df = pd.DataFrame(data["products"])
df.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,dimensions,warrantyInformation,shippingInformation,availabilityStatus,reviews,returnPolicy,minimumOrderQuantity,meta,images,thumbnail
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,"{'width': 15.14, 'height': 13.08, 'depth': 22.99}",1 week warranty,Ships in 3-5 business days,In Stock,"[{'rating': 3, 'comment': 'Would not recommend...",No return policy,48,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,"{'width': 9.26, 'height': 22.47, 'depth': 27.67}",1 year warranty,Ships in 2 weeks,In Stock,"[{'rating': 5, 'comment': 'Great product!', 'd...",7 days return policy,20,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,"{'width': 29.27, 'height': 27.93, 'depth': 20.59}",3 months warranty,Ships in 1-2 business days,In Stock,"[{'rating': 4, 'comment': 'Would buy again!', ...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,"{'width': 18.11, 'height': 28.38, 'depth': 22.17}",3 year warranty,Ships in 1 week,In Stock,"[{'rating': 4, 'comment': 'Great product!', 'd...",7 days return policy,40,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,"{'width': 21.63, 'height': 16.48, 'depth': 29.84}",1 month warranty,Ships overnight,In Stock,"[{'rating': 2, 'comment': 'Poor quality!', 'da...",No return policy,22,"{'createdAt': '2025-04-30T09:41:02.053Z', 'upd...",[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...

4. Se validó la información del DataFrame, identificando los tipos de datos de cada columna, la presencia de valores vacíos, así como la cantidad y el tipo de columnas disponibles.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    100 non-null    int64
 1   title                 100 non-null    object
 2   description           100 non-null    object
 3   category              100 non-null    object
 4   price                 100 non-null    float64
 5   discountPercentage    100 non-null    float64
 6   rating                100 non-null    float64
 7   stock                 100 non-null    int64
 8   tags                  100 non-null    object
 9   brand                 38 non-null     object
 10  sku                   100 non-null    object
 11  weight                100 non-null    int64
 12  dimensions            100 non-null    object
 13  warrantyInformation   100 non-null    object
 14  shippingInformation   100 non-null    object
 15  availabilityStatus    100 non-null    object
 16  reviews               100 non-null    object
 17  returnPolicy          100 non-null    object
 18  minimumOrderQuantity  100 non-null    int64
 19  meta                  100 non-null    object
 20  images                100 non-null    object
 21  thumbnail             100 non-null    object
dtypes: float64(3), int64(4), object(15)
memory usage: 17.3+ KB

5. Se consultaron desde la API las categorías disponibles de los productos, utilizando el endpoint:  */products/categories*

In [6]:
endpoint_categorias = "/products/categories"
url_categorias = base_url + endpoint_categorias
reponse_categorias = requests.get(url_categorias)
categorias = reponse_categorias.json()
print(categorias)

[{'slug': 'beauty', 'name': 'Beauty', 'url': 'https://dummyjson.com/products/category/beauty'}, {'slug': 'fragrances', 'name': 'Fragrances', 'url': 'https://dummyjson.com/products/category/fragrances'}, {'slug': 'furniture', 'name': 'Furniture', 'url': 'https://dummyjson.com/products/category/furniture'}, {'slug': 'groceries', 'name': 'Groceries', 'url': 'https://dummyjson.com/products/category/groceries'}, {'slug': 'home-decoration', 'name': 'Home Decoration', 'url': 'https://dummyjson.com/products/category/home-decoration'}, {'slug': 'kitchen-accessories', 'name': 'Kitchen Accessories', 'url': 'https://dummyjson.com/products/category/kitchen-accessories'}, {'slug': 'laptops', 'name': 'Laptops', 'url': 'https://dummyjson.com/products/category/laptops'}, {'slug': 'mens-shirts', 'name': 'Mens Shirts', 'url': 'https://dummyjson.com/products/category/mens-shirts'}, {'slug': 'mens-shoes', 'name': 'Mens Shoes', 'url': 'https://dummyjson.com/products/category/mens-shoes'}, {'slug': 'mens-watches', 'name': 'Mens Watches', 'url': 'https://dummyjson.com/products/category/mens-watches'}, {'slug': 'mobile-accessories', 'name': 'Mobile Accessories', 'url': 'https://dummyjson.com/products/category/mobile-accessories'}, {'slug': 'motorcycle', 'name': 'Motorcycle', 'url': 'https://dummyjson.com/products/category/motorcycle'}, {'slug': 'skin-care', 'name': 'Skin Care', 'url': 'https://dummyjson.com/products/category/skin-care'}, {'slug': 'smartphones', 'name': 'Smartphones', 'url': 'https://dummyjson.com/products/category/smartphones'}, {'slug': 'sports-accessories', 'name': 'Sports Accessories', 'url': 'https://dummyjson.com/products/category/sports-accessories'}, {'slug': 'sunglasses', 'name': 'Sunglasses', 'url': 'https://dummyjson.com/products/category/sunglasses'}, {'slug': 'tablets', 'name': 'Tablets', 'url': 'https://dummyjson.com/products/category/tablets'}, {'slug': 'tops', 'name': 'Tops', 'url': 'https://dummyjson.com/products/category/tops'}, {'slug': 'vehicle', 'name': 'Vehicle', 'url': 'https://dummyjson.com/products/category/vehicle'}, {'slug': 'womens-bags', 'name': 'Womens Bags', 'url': 'https://dummyjson.com/products/category/womens-bags'}, {'slug': 'womens-dresses', 'name': 'Womens Dresses', 'url': 'https://dummyjson.com/products/category/womens-dresses'}, {'slug': 'womens-jewellery', 'name': 'Womens Jewellery', 'url': 'https://dummyjson.com/products/category/womens-jewellery'}, {'slug': 'womens-shoes', 'name': 'Womens Shoes', 'url': 'https://dummyjson.com/products/category/womens-shoes'}, {'slug': 'womens-watches', 'name': 'Womens Watches', 'url': 'https://dummyjson.com/products/category/womens-watches'}]

6. Se eliminaron las columnas: description, sku, weight, dimensions, arrantyInformation, shippingInformation, returnPolicy, reviews, meta, images y thumbnail, debido a que la informacion que contienen no resulta relevante para el analisis.

In [7]:
df = df.drop(columns=["description","sku","weight","dimensions","warrantyInformation","shippingInformation","returnPolicy","reviews","meta","images","thumbnail"])
df

,id,title,category,price,discountPercentage,rating,stock,tags,brand,availabilityStatus,minimumOrderQuantity
0,1,Essence Mascara Lash Princess,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,In Stock,48
1,2,Eyeshadow Palette with Mirror,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,In Stock,20
2,3,Powder Canister,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,In Stock,22
3,4,Red Lipstick,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,In Stock,40
4,5,Red Nail Polish,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,In Stock,22
...,...,...,...,...,...,...,...,...,...,...,...
95,96,Rolex Cellini Moonphase,mens-watches,12999.99,17.52,2.58,36,"[watches, luxury watches]",Rolex,In Stock,1
96,97,Rolex Datejust,mens-watches,10999.99,3.73,3.66,86,"[watches, luxury watches]",Rolex,In Stock,1
97,98,Rolex Submariner Watch,mens-watches,13999.99,5.05,2.69,55,"[watches, luxury watches]",Rolex,In Stock,1
98,99,Amazon Echo Plus,mobile-accessories,99.99,12.07,4.99,61,"[electronics, smart speakers]",Amazon,In Stock,9
99,100,Apple Airpods,mobile-accessories,129.99,15.54,4.15,67,"[electronics, wireless earphones]",Apple,In Stock,4

7. En el paso 4 se evidenció que la columna brand no se encontraba completamente diligenciada, ya que presentaba valores nulos. Por esta razón, se procedió a reemplazarlos con el valor "Unknown", con el fin de mantener la integridad del dataset y permitir el análisis completo de los datos sin pérdida de registros.

In [8]:
df["brand"] = df["brand"].fillna("Unknown")
df.head()

,id,title,category,price,discountPercentage,rating,stock,tags,brand,availabilityStatus,minimumOrderQuantity
0,1,Essence Mascara Lash Princess,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,In Stock,48
1,2,Eyeshadow Palette with Mirror,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,In Stock,20
2,3,Powder Canister,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,In Stock,22
3,4,Red Lipstick,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,In Stock,40
4,5,Red Nail Polish,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,In Stock,22

8. Se creo la columna indice para combinar la calificación del producto y la disponibilidad en inventario, lo anterior con el objetivo de identificar productos que no solo son bien valorados por los usuarios, sino que también tienen suficiente stock para su venta.

In [9]:
df["indice"] = df["rating"] * df["stock"]
df

,id,title,category,price,discountPercentage,rating,stock,tags,brand,availabilityStatus,minimumOrderQuantity,indice
0,1,Essence Mascara Lash Princess,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,In Stock,48,253.44
1,2,Eyeshadow Palette with Mirror,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,In Stock,20,97.24
2,3,Powder Canister,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,In Stock,22,412.96
3,4,Red Lipstick,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,In Stock,40,396.76
4,5,Red Nail Polish,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,In Stock,22,341.28
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Rolex Cellini Moonphase,mens-watches,12999.99,17.52,2.58,36,"[watches, luxury watches]",Rolex,In Stock,1,92.88
96,97,Rolex Datejust,mens-watches,10999.99,3.73,3.66,86,"[watches, luxury watches]",Rolex,In Stock,1,314.76
97,98,Rolex Submariner Watch,mens-watches,13999.99,5.05,2.69,55,"[watches, luxury watches]",Rolex,In Stock,1,147.95
98,99,Amazon Echo Plus,mobile-accessories,99.99,12.07,4.99,61,"[electronics, smart speakers]",Amazon,In Stock,9,304.39
99,100,Apple Airpods,mobile-accessories,129.99,15.54,4.15,67,"[electronics, wireless earphones]",Apple,In Stock,4,278.05

9. Se creó la columna relación precio vs rating para analizar si un producto es costoso en comparación con la valoración que recibe, lo que permite identificar aquellos productos que pueden percibirse como “caros” o que tienen una menor relación calidad-precio.

In [10]:
df["relacion_precio_rating"] = df["price"] / df["rating"]
df

,id,title,category,price,discountPercentage,rating,stock,tags,brand,availabilityStatus,minimumOrderQuantity,indice,relacion_precio_rating
0,1,Essence Mascara Lash Princess,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,In Stock,48,253.44,3.902344
1,2,Eyeshadow Palette with Mirror,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,In Stock,20,97.24,6.989510
2,3,Powder Canister,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,In Stock,22,412.96,3.230603
3,4,Red Lipstick,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,In Stock,40,396.76,2.979358
4,5,Red Nail Polish,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,In Stock,22,341.28,2.081019
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Rolex Cellini Moonphase,mens-watches,12999.99,17.52,2.58,36,"[watches, luxury watches]",Rolex,In Stock,1,92.88,5038.755814
96,97,Rolex Datejust,mens-watches,10999.99,3.73,3.66,86,"[watches, luxury watches]",Rolex,In Stock,1,314.76,3005.461749
97,98,Rolex Submariner Watch,mens-watches,13999.99,5.05,2.69,55,"[watches, luxury watches]",Rolex,In Stock,1,147.95,5204.457249
98,99,Amazon Echo Plus,mobile-accessories,99.99,12.07,4.99,61,"[electronics, smart speakers]",Amazon,In Stock,9,304.39,20.038076
99,100,Apple Airpods,mobile-accessories,129.99,15.54,4.15,67,"[electronics, wireless earphones]",Apple,In Stock,4,278.05,31.322892

10. Se cambiaron los nombres de las columnas con el objetivo de facilitar la comprensión de los datos y mejorar su uso en el análisis dentro de Power BI, haciendo el dataset más organizado y fácil de interpretar.

In [11]:
df = df.rename(columns={
    "id": "ID",
    "title": "Producto",
    "category": "Categoria",
    "price": "Precio unitario",
    "discountPercentage": "Descuento",
    "rating": "Puntaje",
    "stock": "Cantidad disponible",
    "tags": "Etiquetas",
    "brand": "Marca",
    "availabilityStatus": "Disponibilidad",
    "minimumOrderQuantity": "Cantidad minima",
    "indice": "Indice Puntaje vs Stock",
    "relacion_precio_rating": "Relacion Precio vs Puntaje",
})
df

,ID,Producto,Categoria,Precio unitario,Descuento,Puntaje,Cantidad disponible,Etiquetas,Marca,Disponibilidad,Cantidad minima,Indice Puntaje vs Stock,Relacion Precio vs Puntaje
0,1,Essence Mascara Lash Princess,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,In Stock,48,253.44,3.902344
1,2,Eyeshadow Palette with Mirror,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,In Stock,20,97.24,6.989510
2,3,Powder Canister,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,In Stock,22,412.96,3.230603
3,4,Red Lipstick,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,In Stock,40,396.76,2.979358
4,5,Red Nail Polish,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,In Stock,22,341.28,2.081019
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Rolex Cellini Moonphase,mens-watches,12999.99,17.52,2.58,36,"[watches, luxury watches]",Rolex,In Stock,1,92.88,5038.755814
96,97,Rolex Datejust,mens-watches,10999.99,3.73,3.66,86,"[watches, luxury watches]",Rolex,In Stock,1,314.76,3005.461749
97,98,Rolex Submariner Watch,mens-watches,13999.99,5.05,2.69,55,"[watches, luxury watches]",Rolex,In Stock,1,147.95,5204.457249
98,99,Amazon Echo Plus,mobile-accessories,99.99,12.07,4.99,61,"[electronics, smart speakers]",Amazon,In Stock,9,304.39,20.038076
99,100,Apple Airpods,mobile-accessories,129.99,15.54,4.15,67,"[electronics, wireless earphones]",Apple,In Stock,4,278.05,31.322892

In [17]:
df["Precio unitario"] = df["Precio unitario"].round(2)
df["Relacion Precio vs Puntaje"] = df["Relacion Precio vs Puntaje"].round(2)
df

,ID,Producto,Categoria,Precio unitario,Descuento,Puntaje,Cantidad disponible,Etiquetas,Marca,Disponibilidad,Cantidad minima,Indice Puntaje vs Stock,Relacion Precio vs Puntaje
0,1,Essence Mascara Lash Princess,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,In Stock,48,253.44,3.90
1,2,Eyeshadow Palette with Mirror,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,In Stock,20,97.24,6.99
2,3,Powder Canister,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,In Stock,22,412.96,3.23
3,4,Red Lipstick,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,In Stock,40,396.76,2.98
4,5,Red Nail Polish,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,In Stock,22,341.28,2.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Rolex Cellini Moonphase,mens-watches,12999.99,17.52,2.58,36,"[watches, luxury watches]",Rolex,In Stock,1,92.88,5038.76
96,97,Rolex Datejust,mens-watches,10999.99,3.73,3.66,86,"[watches, luxury watches]",Rolex,In Stock,1,314.76,3005.46
97,98,Rolex Submariner Watch,mens-watches,13999.99,5.05,2.69,55,"[watches, luxury watches]",Rolex,In Stock,1,147.95,5204.46
98,99,Amazon Echo Plus,mobile-accessories,99.99,12.07,4.99,61,"[electronics, smart speakers]",Amazon,In Stock,9,304.39,20.04
99,100,Apple Airpods,mobile-accessories,129.99,15.54,4.15,67,"[electronics, wireless earphones]",Apple,In Stock,4,278.05,31.32

11. Se validó la cantidad de productos por categoría con el objetivo de entender cómo se distribuye el catálogo y analizar la concentración de productos.

In [12]:
df.columns

Index(['ID', 'Producto', 'Categoria', 'Precio unitario', 'Descuento',
       'Puntaje', 'Cantidad disponible', 'Etiquetas', 'Marca',
       'Disponibilidad', 'Cantidad minima', 'Indice Puntaje vs Stock',
       'Relacion Precio vs Puntaje'],
      dtype='object')

In [13]:
df['Categoria'].value_counts()

Categoria
kitchen-accessories    30
groceries              27
mens-watches            6
furniture               5
fragrances              5
beauty                  5
home-decoration         5
laptops                 5
mens-shirts             5
mens-shoes              5
mobile-accessories      2
Name: count, dtype: int64

12. Se realizo descarga de los datos en formato CSV.

In [18]:
df.to_csv('Taller 3 Catalina Igua C.csv', index=False)

In [19]:
import os
os.listdir()

['.config', 'Taller 3 Catalina Igua C.csv', 'sample_data']

In [20]:
from google.colab import files
files.download('Taller 3 Catalina Igua C.csv')